'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8806
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GuiaFletesGAG.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actionsdrawerasericon96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actionsdrawerasericon96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Appsaccessoriescalculatoricon96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appsaccessoriescalculatoricon96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property binocularsicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("binocularsicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property binocularsicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("binocularsicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property binocularsicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("binocularsicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property binocularsicon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("binocularsicon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property books() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("books", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Calculatoricon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calculatoricon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calculatoricon16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calculatoricon16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calculatoricon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calculatoricon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calculatoricon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calculatoricon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cargo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Cargo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property cargo1icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargo1icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cargo1icon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargo1icon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cargo1icon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargo1icon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cargo1icon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargo1icon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cargo1icon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargo1icon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ColumnCharticon2128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColumnCharticon2128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ColumnCharticon224() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColumnCharticon224", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ColumnCharticon232() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColumnCharticon232", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ColumnCharticon248() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColumnCharticon248", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ColumnCharticon264() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColumnCharticon264", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DeviceFloppyicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeviceFloppyicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DeviceFloppyicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeviceFloppyicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DeviceFloppyicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeviceFloppyicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DeviceFloppyicon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeviceFloppyicon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FileBlankicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileBlankicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FileBlankicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileBlankicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FileBlankicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileBlankicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FileBlankicon32pixel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileBlankicon32pixel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FileBlankicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileBlankicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FileBlankicon64pixel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileBlankicon64pixel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FileBlankicon72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileBlankicon72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilesEditfileicon96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilesEditfileicon96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gear() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property HydrattzMultipurposeAlphabetLetterCblue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HydrattzMultipurposeAlphabetLetterCblue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property HydrattzMultipurposeAlphabetLetterIblue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HydrattzMultipurposeAlphabetLetterIblue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property HydrattzMultipurposeAlphabetLetterPblue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HydrattzMultipurposeAlphabetLetterPblue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property HydrattzMultipurposeAlphabetLetterRblue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HydrattzMultipurposeAlphabetLetterRblue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property HydrattzMultipurposeAlphabetLetterSblue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HydrattzMultipurposeAlphabetLetterSblue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property InternetExplorer() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("InternetExplorer", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceicon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceicon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogOuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogOuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogOuicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogOuicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogOuicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogOuicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogOuicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogOuicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogOuicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogOuicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property okicon96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okicon96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OOCL4icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OOCL4icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OOCL4icon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OOCL4icon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OOCL4icon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OOCL4icon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Outlook() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Outlook", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property refreshicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refreshicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refreshicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refreshicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refreshicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refreshicon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshicon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignAddicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignAddicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignAddicon32pixel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignAddicon32pixel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignAddicon64pixel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignAddicon64pixel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignErroricon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignErroricon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignErroricon32pixel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignErroricon32pixel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignErroricon64pixel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignErroricon64pixel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignStopicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignStopicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignStopicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignStopicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignStopicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignStopicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignStopicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignStopicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignStopicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignStopicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignStopicon64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignStopicon64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignStopicon72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignStopicon72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Thumbs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Thumbs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property toolicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolicon128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolicon128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolicon24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolicon24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolicon48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolicon48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property YellowPagesBook() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowPagesBook", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
